apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: minio-sync
spec:
  schedule: "*/5 * * * *"
  workflowSpec:
    entrypoint: sync-files
    volumes:
    - name: minio-secret
      secret:
        secretName: minio-creds
     
    templates:
    - name: sync-files
      steps:
      - - name: sync-from-minio
          template: minio-sync
        
    - name: minio-sync
      container:
        name: copy-from-minio
        image: minio/mc
        command: ["sh", "-c"]
        args: ["mc alias set myminio http://minio.minio.svc.cluster.local:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && mc alias set myminio2 http://minio.web.svc.cluster.local:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && mc mirror --overwrite myminio/uploads/ myminio2/uploads/"]
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: accesskey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: secretkey
